# Site settings
title: "Mirfield Evangelical Church"
email: "mirfieldchurch@gmail.com"
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

facebook_page:
base_address: "Wellhouse Lane, Mirfield, West Yorkshire WF14 0AN United Kingdom"
phone_number: "01924 499189"

# Build settings
markdown: kramdown
